---

- name: 3.1.Setup Swarm Cluster
  include: setup-swarm-cluster.yml
  when: not skip_swarm
  tags:
    - setup-docker-swarm
    - setup-swarm-cluster

- name: 3.2.Setup Swarm Labels
  include: setup-swarm-labels.yml
  when: not skip_swarm_labels
  tags:
    - setup-docker-swarm
    - setup-swarm-labels
