---
- name: 2.3.1.Install bash-completion (for docker command auto-completion)
  package:
    name: bash-completion
    state: present
  tags:
    - install-docker-core
    - install-docker-autocompletion

- name: 2.3.2.Download the docker-autocompletion script
  get_url:
    url: "https://raw.githubusercontent.com/docker/docker-ce/master/components/cli/contrib/completion/bash/docker"
    dest: "/etc/bash_completion.d/docker"
    mode: '0644'
    timeout: 180
  tags:
    - install-docker-core
    - install-docker-autocompletion
